### PR TITLE
fix: fixed search while not a first page

### PR DESCRIPTION
**Pull request by wernervdk**
fix for issue #333

- The fix is a reset of the selected page when paging is active while searching
- Added test with search action from page 2
- Fixed a typing for event

### CODE REVIEW

**Comment by ssuperczynski** [comment]
Thanks @wernervdk, could you check this test. It is failing

**Comment by wernervdk** [comment]
I checked the tests and on a windows 11 machine it works correctly, see the at attached log file.

For now i only set the version of the library back to 15.0.0.

If i'm doing something wrong, please let me know.



[result cy tests.txt](https://github.com/ssuperczynski/ngx-easy-table/files/7482240/result.cy.tests.txt)

**Comment by kalmargabor92** [comment]
@ssuperczynski could you please re-review the changes?

**Comment by ssuperczynski** [comment]
merged here https://github.com/ssuperczynski/ngx-easy-table/pull/398

**Pull request closed without merging**
